"""Initial migration

Revision ID: 095ba3220dbd
Revises: 
Create Date: 2026-06-22 09:27:39.497733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '095ba3220dbd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orgs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_org_id'), 'projects', ['org_id'], unique=False)
    op.create_table('media_assets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=True),
    sa.Column('storage_key', sa.String(length=512), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_assets_org_id'), 'media_assets', ['org_id'], unique=False)
    op.create_index(op.f('ix_media_assets_project_id'), 'media_assets', ['project_id'], unique=False)
    op.create_table('transcripts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('source_media_id', sa.String(length=32), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('transcription_status', sa.String(length=32), nullable=True),
    sa.Column('transcription_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_media_id'], ['media_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcripts_org_id'), 'transcripts', ['org_id'], unique=False)
    op.create_index(op.f('ix_transcripts_project_id'), 'transcripts', ['project_id'], unique=False)
    op.create_table('analyses',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('transcript_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('topline', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('respondent_count', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_org_id'), 'analyses', ['org_id'], unique=False)
    op.create_index(op.f('ix_analyses_transcript_id'), 'analyses', ['transcript_id'], unique=False)
    op.create_table('transcript_segments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('transcript_id', sa.String(length=32), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=True),
    sa.Column('speaker', sa.String(length=64), nullable=True),
    sa.Column('start_sec', sa.Float(), nullable=True),
    sa.Column('end_sec', sa.Float(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcript_segments_transcript_id'), 'transcript_segments', ['transcript_id'], unique=False)
    op.create_table('implications',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('analysis_id', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('order_idx', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_implications_analysis_id'), 'implications', ['analysis_id'], unique=False)
    op.create_table('themes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('analysis_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prevalence', sa.String(length=32), nullable=True),
    sa.Column('sentiment', sa.String(length=32), nullable=True),
    sa.Column('order_idx', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_themes_analysis_id'), 'themes', ['analysis_id'], unique=False)
    op.create_table('usage_records',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('analysis_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_records_org_id'), 'usage_records', ['org_id'], unique=False)
    op.create_table('verbatims',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('theme_id', sa.String(length=32), nullable=False),
    sa.Column('quote', sa.Text(), nullable=True),
    sa.Column('speaker', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verbatims_theme_id'), 'verbatims', ['theme_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verbatims_theme_id'), table_name='verbatims')
    op.drop_table('verbatims')
    op.drop_index(op.f('ix_usage_records_org_id'), table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index(op.f('ix_themes_analysis_id'), table_name='themes')
    op.drop_table('themes')
    op.drop_index(op.f('ix_implications_analysis_id'), table_name='implications')
    op.drop_table('implications')
    op.drop_index(op.f('ix_transcript_segments_transcript_id'), table_name='transcript_segments')
    op.drop_table('transcript_segments')
    op.drop_index(op.f('ix_analyses_transcript_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_org_id'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_transcripts_project_id'), table_name='transcripts')
    op.drop_index(op.f('ix_transcripts_org_id'), table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index(op.f('ix_media_assets_project_id'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_org_id'), table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index(op.f('ix_projects_org_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('orgs')
    # ### end Alembic commands ###
