"""reconcile schema with models (create tables missing from chain)

Revision ID: 0c2580351b01
Revises: e2b3c4d5f6a7
Create Date: 2026-06-30 17:36:37.731715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c2580351b01'
down_revision: Union[str, Sequence[str], None] = 'e2b3c4d5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Lets SQLite batch_alter_table name the unnamed constraints it reflects when it
# has to recreate import_jobs to add the integration_id foreign key.
_NAMING = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s",
    "pk": "pk_%(table_name)s",
}


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integrations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usage_quotas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('storage_quota_gb', sa.Float(), nullable=True),
    sa.Column('storage_used_gb', sa.Float(), nullable=True),
    sa.Column('user_quota', sa.Integer(), nullable=True),
    sa.Column('users_active', sa.Integer(), nullable=True),
    sa.Column('project_quota', sa.Integer(), nullable=True),
    sa.Column('projects_active', sa.Integer(), nullable=True),
    sa.Column('ai_calls_quota', sa.Integer(), nullable=True),
    sa.Column('ai_calls_used', sa.Integer(), nullable=True),
    sa.Column('ai_tokens_quota', sa.Integer(), nullable=True),
    sa.Column('ai_tokens_used', sa.Integer(), nullable=True),
    sa.Column('video_processing_minutes_quota', sa.Integer(), nullable=True),
    sa.Column('video_processing_minutes_used', sa.Integer(), nullable=True),
    sa.Column('audio_processing_minutes_quota', sa.Integer(), nullable=True),
    sa.Column('audio_processing_minutes_used', sa.Integer(), nullable=True),
    sa.Column('exports_quota', sa.Integer(), nullable=True),
    sa.Column('exports_used', sa.Integer(), nullable=True),
    sa.Column('api_rate_limit', sa.Integer(), nullable=True),
    sa.Column('billing_tier', sa.String(length=20), nullable=True),
    sa.Column('billing_cycle', sa.String(length=20), nullable=True),
    sa.Column('next_reset_date', sa.DateTime(), nullable=True),
    sa.Column('storage_alert_threshold', sa.Float(), nullable=True),
    sa.Column('ai_alert_threshold', sa.Float(), nullable=True),
    sa.Column('alert_emails', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_reset_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('projects_active <= project_quota', name='check_project_limit'),
    sa.CheckConstraint('storage_used_gb <= storage_quota_gb', name='check_storage_limit'),
    sa.CheckConstraint('users_active <= user_quota', name='check_user_limit'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id')
    )
    with op.batch_alter_table('usage_quotas', schema=None) as batch_op:
        batch_op.create_index('ix_quota_org', ['org_id'], unique=False)

    op.create_table('white_label_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('brand_name', sa.String(length=100), nullable=False),
    sa.Column('brand_logo_url', sa.String(length=500), nullable=True),
    sa.Column('brand_favicon_url', sa.String(length=500), nullable=True),
    sa.Column('brand_colors', sa.JSON(), nullable=True),
    sa.Column('custom_domain', sa.String(length=255), nullable=True),
    sa.Column('ssl_certificate', sa.Text(), nullable=True),
    sa.Column('ssl_key', sa.Text(), nullable=True),
    sa.Column('email_from_name', sa.String(length=100), nullable=True),
    sa.Column('email_from_address', sa.String(length=255), nullable=True),
    sa.Column('email_smtp_host', sa.String(length=255), nullable=True),
    sa.Column('email_smtp_port', sa.Integer(), nullable=True),
    sa.Column('email_smtp_user', sa.String(length=255), nullable=True),
    sa.Column('email_smtp_password', sa.Text(), nullable=True),
    sa.Column('email_template_header', sa.Text(), nullable=True),
    sa.Column('email_template_footer', sa.Text(), nullable=True),
    sa.Column('default_language', sa.String(length=10), nullable=True),
    sa.Column('supported_languages', sa.JSON(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('enable_ai_insights', sa.Boolean(), nullable=True),
    sa.Column('enable_video_processing', sa.Boolean(), nullable=True),
    sa.Column('enable_collaboration', sa.Boolean(), nullable=True),
    sa.Column('enable_statistical_analysis', sa.Boolean(), nullable=True),
    sa.Column('enable_code_mixing', sa.Boolean(), nullable=True),
    sa.Column('enable_concept_testing', sa.Boolean(), nullable=True),
    sa.Column('custom_features', sa.JSON(), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('max_projects', sa.Integer(), nullable=True),
    sa.Column('max_storage_gb', sa.Float(), nullable=True),
    sa.Column('max_ai_calls_per_month', sa.Integer(), nullable=True),
    sa.Column('terms_url', sa.String(length=500), nullable=True),
    sa.Column('privacy_url', sa.String(length=500), nullable=True),
    sa.Column('gdpr_compliant', sa.Boolean(), nullable=True),
    sa.Column('pdpa_compliant', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id')
    )
    with op.batch_alter_table('white_label_configs', schema=None) as batch_op:
        batch_op.create_index('ix_white_label_custom_domain', ['custom_domain'], unique=False)
        batch_op.create_index('ix_white_label_org_id', ['org_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('entity_name', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('request_method', sa.String(length=10), nullable=True),
    sa.Column('request_path', sa.String(length=500), nullable=True),
    sa.Column('request_params', sa.JSON(), nullable=True),
    sa.Column('request_body', sa.JSON(), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('data_classification', sa.String(length=20), nullable=True),
    sa.Column('contains_pii', sa.Boolean(), nullable=True),
    sa.Column('gdpr_relevant', sa.Boolean(), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_action', ['action'], unique=False)
        batch_op.create_index('ix_audit_created', ['created_at'], unique=False)
        batch_op.create_index('ix_audit_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('ix_audit_ip', ['ip_address'], unique=False)
        batch_op.create_index('ix_audit_org_user', ['org_id', 'user_id'], unique=False)

    op.create_table('chat_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('initial_messages', sa.JSON(), nullable=True),
    sa.Column('suggested_questions', sa.JSON(), nullable=True),
    sa.Column('use_case', sa.String(length=64), nullable=True),
    sa.Column('research_type', sa.String(length=64), nullable=True),
    sa.Column('market_specific', sa.Boolean(), nullable=True),
    sa.Column('target_markets', sa.JSON(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_templates', schema=None) as batch_op:
        batch_op.create_index('idx_chat_template_org', ['org_id'], unique=False)
        batch_op.create_index('idx_chat_template_use_case', ['use_case'], unique=False)

    op.create_table('clip_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('criteria', sa.JSON(), nullable=True),
    sa.Column('max_duration', sa.Float(), nullable=True),
    sa.Column('include_context_before', sa.Float(), nullable=True),
    sa.Column('include_context_after', sa.Float(), nullable=True),
    sa.Column('title_template', sa.Text(), nullable=True),
    sa.Column('subtitle_template', sa.Text(), nullable=True),
    sa.Column('overlay_style', sa.JSON(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clip_templates', schema=None) as batch_op:
        batch_op.create_index('idx_clip_template_category', ['category'], unique=False)
        batch_op.create_index('idx_clip_template_org', ['org_id'], unique=False)

    op.create_table('custom_fields',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=False),
    sa.Column('field_label', sa.String(length=100), nullable=False),
    sa.Column('field_type', sa.String(length=20), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('validation_rules', sa.JSON(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('show_in_list', sa.Boolean(), nullable=True),
    sa.Column('show_in_export', sa.Boolean(), nullable=True),
    sa.Column('translations', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'entity_type', 'field_name', name='uq_org_entity_field')
    )
    with op.batch_alter_table('custom_fields', schema=None) as batch_op:
        batch_op.create_index('ix_custom_field_org_entity', ['org_id', 'entity_type'], unique=False)

    op.create_table('data_export_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('export_type', sa.String(length=50), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('project_ids', sa.JSON(), nullable=True),
    sa.Column('date_from', sa.DateTime(), nullable=True),
    sa.Column('date_to', sa.DateTime(), nullable=True),
    sa.Column('include_transcripts', sa.Boolean(), nullable=True),
    sa.Column('include_analysis', sa.Boolean(), nullable=True),
    sa.Column('include_media', sa.Boolean(), nullable=True),
    sa.Column('include_deleted', sa.Boolean(), nullable=True),
    sa.Column('anonymize_pii', sa.Boolean(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=100), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_size_mb', sa.Float(), nullable=True),
    sa.Column('download_url', sa.String(length=500), nullable=True),
    sa.Column('download_expires', sa.DateTime(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=True),
    sa.Column('records_exported', sa.Integer(), nullable=True),
    sa.Column('processing_time_seconds', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_export_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_export_created', ['created_at'], unique=False)
        batch_op.create_index('ix_export_org_user', ['org_id', 'user_id'], unique=False)
        batch_op.create_index('ix_export_status', ['status'], unique=False)

    op.create_table('data_import_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('import_type', sa.String(length=50), nullable=False),
    sa.Column('source_format', sa.String(length=20), nullable=False),
    sa.Column('source_system', sa.String(length=50), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size_mb', sa.Float(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('field_mappings', sa.JSON(), nullable=True),
    sa.Column('default_values', sa.JSON(), nullable=True),
    sa.Column('validate_only', sa.Boolean(), nullable=True),
    sa.Column('skip_duplicates', sa.Boolean(), nullable=True),
    sa.Column('merge_strategy', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=100), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('records_imported', sa.Integer(), nullable=True),
    sa.Column('records_skipped', sa.Integer(), nullable=True),
    sa.Column('records_failed', sa.Integer(), nullable=True),
    sa.Column('validation_errors', sa.JSON(), nullable=True),
    sa.Column('validation_warnings', sa.JSON(), nullable=True),
    sa.Column('created_projects', sa.JSON(), nullable=True),
    sa.Column('created_transcripts', sa.JSON(), nullable=True),
    sa.Column('processing_time_seconds', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('failed_records', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_import_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_import_created', ['created_at'], unique=False)
        batch_op.create_index('ix_import_org_user', ['org_id', 'user_id'], unique=False)
        batch_op.create_index('ix_import_status', ['status'], unique=False)

    op.create_table('integration_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('integration_type', sa.String(length=50), nullable=False),
    sa.Column('integration_name', sa.String(length=100), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('credentials', sa.JSON(), nullable=True),
    sa.Column('webhook_url', sa.String(length=500), nullable=True),
    sa.Column('webhook_secret', sa.String(length=255), nullable=True),
    sa.Column('webhook_events', sa.JSON(), nullable=True),
    sa.Column('oauth_token', sa.Text(), nullable=True),
    sa.Column('oauth_refresh_token', sa.Text(), nullable=True),
    sa.Column('oauth_expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('supports_multilingual', sa.Boolean(), nullable=True),
    sa.Column('default_language', sa.String(length=10), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'integration_type', 'integration_name', name='uq_org_integration')
    )
    with op.batch_alter_table('integration_configs', schema=None) as batch_op:
        batch_op.create_index('ix_integration_org', ['org_id'], unique=False)
        batch_op.create_index('ix_integration_type', ['integration_type'], unique=False)

    op.create_table('media_processing_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.String(length=32), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('celery_task_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('input_size_mb', sa.Float(), nullable=True),
    sa.Column('output_size_mb', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media_processing_jobs', schema=None) as batch_op:
        batch_op.create_index('idx_media_job_created', ['created_at'], unique=False)
        batch_op.create_index('idx_media_job_status', ['status'], unique=False)
        batch_op.create_index('idx_media_job_target', ['target_type', 'target_id'], unique=False)

    op.create_table('saved_prompts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prompt_template', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saved_prompts', schema=None) as batch_op:
        batch_op.create_index('idx_saved_prompt_category', ['category'], unique=False)
        batch_op.create_index('idx_saved_prompt_org', ['org_id', 'is_public'], unique=False)

    op.create_table('share_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.Column('allow_download', sa.Boolean(), nullable=True),
    sa.Column('require_email', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('max_views', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('unique_viewers', sa.Integer(), nullable=True),
    sa.Column('last_viewed', sa.DateTime(), nullable=True),
    sa.Column('viewer_emails', sa.JSON(), nullable=True),
    sa.Column('view_analytics', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('share_links', schema=None) as batch_op:
        batch_op.create_index('idx_share_link_expires', ['expires_at'], unique=False)
        batch_op.create_index('idx_share_link_target', ['target_type', 'target_id'], unique=False)
        batch_op.create_index('idx_share_link_token', ['token'], unique=False)

    op.create_table('analysis_grids',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('analysis_type', sa.Enum('BASIC', 'COMPARATIVE', 'MULTIMARKET', 'LONGITUDINAL', 'SEGMENT', name='analysistype'), nullable=True),
    sa.Column('grid_type', sa.Enum('THEMES', 'QUESTIONS', 'CONCEPTS', 'JOURNEY', 'PERSONAS', name='gridtype'), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('columns', sa.JSON(), nullable=True),
    sa.Column('rows', sa.JSON(), nullable=True),
    sa.Column('comparison_dimensions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_themes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('evidence_count', sa.Integer(), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['analysis_themes.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_themes', schema=None) as batch_op:
        batch_op.create_index('idx_theme_hierarchy', ['parent_id', 'level'], unique=False)
        batch_op.create_index('idx_theme_project', ['project_id'], unique=False)

    op.create_table('chat_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('context_window', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('total_messages', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.create_index('idx_chat_session_project', ['project_id'], unique=False)
        batch_op.create_index('idx_chat_session_user', ['user_id'], unique=False)

    op.create_table('collaboration_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('session_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collaboration_sessions', schema=None) as batch_op:
        batch_op.create_index('idx_collab_session', ['project_id', 'status'], unique=False)
        batch_op.create_index('idx_collab_user', ['user_id', 'status'], unique=False)

    op.create_table('community_threads',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('posts', sa.JSON(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom_field_values',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('custom_field_id', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('text_value', sa.Text(), nullable=True),
    sa.Column('number_value', sa.Float(), nullable=True),
    sa.Column('date_value', sa.DateTime(), nullable=True),
    sa.Column('json_value', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['custom_field_id'], ['custom_fields.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('custom_field_id', 'entity_id', name='uq_field_entity')
    )
    with op.batch_alter_table('custom_field_values', schema=None) as batch_op:
        batch_op.create_index('ix_custom_value_field_entity', ['custom_field_id', 'entity_id'], unique=False)

    op.create_table('evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=True),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('evidence_type', sa.String(length=32), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('segment_id', sa.String(length=36), nullable=True),
    sa.Column('speaker', sa.String(length=128), nullable=True),
    sa.Column('start_time', sa.Float(), nullable=True),
    sa.Column('end_time', sa.Float(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('themes', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('significance', sa.String(length=32), nullable=True),
    sa.Column('starred', sa.Boolean(), nullable=True),
    sa.Column('market', sa.String(length=32), nullable=True),
    sa.Column('segment', sa.String(length=128), nullable=True),
    sa.Column('wave', sa.Integer(), nullable=True),
    sa.Column('ai_interpretation', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.Float(), nullable=True),
    sa.Column('emotions', sa.JSON(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index('idx_evidence_project', ['project_id'], unique=False)
        batch_op.create_index('idx_evidence_themes', ['themes'], unique=False)

    op.create_table('insights',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('themes', sa.JSON(), nullable=True),
    sa.Column('priority', sa.String(length=32), nullable=True),
    sa.Column('impact', sa.String(length=32), nullable=True),
    sa.Column('evidence_ids', sa.JSON(), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.Column('markets', sa.JSON(), nullable=True),
    sa.Column('is_regional', sa.Boolean(), nullable=True),
    sa.Column('actionable', sa.Boolean(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('validated', sa.Boolean(), nullable=True),
    sa.Column('validated_by', sa.String(length=36), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['validated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('insights', schema=None) as batch_op:
        batch_op.create_index('idx_insight_priority', ['project_id', 'priority'], unique=False)

    op.create_table('knowledge_bases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_types', sa.JSON(), nullable=True),
    sa.Column('auto_update', sa.Boolean(), nullable=True),
    sa.Column('chunk_size', sa.Integer(), nullable=True),
    sa.Column('chunk_overlap', sa.Integer(), nullable=True),
    sa.Column('total_chunks', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('include_code_mixed', sa.Boolean(), nullable=True),
    sa.Column('primary_language', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_bases', schema=None) as batch_op:
        batch_op.create_index('idx_knowledge_base_project', ['project_id'], unique=False)

    op.create_table('markets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_activities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('activity_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_activities', schema=None) as batch_op:
        batch_op.create_index('idx_activity_user', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('idx_project_activity', ['project_id', 'created_at'], unique=False)

    op.create_table('semantic_search_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('query_embedding', sa.JSON(), nullable=True),
    sa.Column('search_type', sa.String(length=32), nullable=True),
    sa.Column('filters_applied', sa.JSON(), nullable=True),
    sa.Column('top_k', sa.Integer(), nullable=True),
    sa.Column('similarity_threshold', sa.Float(), nullable=True),
    sa.Column('results_count', sa.Integer(), nullable=True),
    sa.Column('result_ids', sa.JSON(), nullable=True),
    sa.Column('result_scores', sa.JSON(), nullable=True),
    sa.Column('search_time_ms', sa.Integer(), nullable=True),
    sa.Column('was_helpful', sa.Boolean(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('semantic_search_logs', schema=None) as batch_op:
        batch_op.create_index('idx_search_log_created', ['created_at'], unique=False)
        batch_op.create_index('idx_search_log_project', ['project_id'], unique=False)
        batch_op.create_index('idx_search_log_user', ['user_id'], unique=False)

    op.create_table('system_metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('metric_unit', sa.String(length=20), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('response_time_p50', sa.Float(), nullable=True),
    sa.Column('response_time_p95', sa.Float(), nullable=True),
    sa.Column('response_time_p99', sa.Float(), nullable=True),
    sa.Column('error_rate', sa.Float(), nullable=True),
    sa.Column('cpu_usage', sa.Float(), nullable=True),
    sa.Column('memory_usage_mb', sa.Float(), nullable=True),
    sa.Column('disk_io_mb', sa.Float(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(length=50), nullable=True),
    sa.Column('ai_provider', sa.String(length=50), nullable=True),
    sa.Column('country_distribution', sa.JSON(), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_metrics', schema=None) as batch_op:
        batch_op.create_index('ix_metrics_org', ['org_id'], unique=False)
        batch_op.create_index('ix_metrics_period', ['period_start', 'period_end'], unique=False)
        batch_op.create_index('ix_metrics_type_name', ['metric_type', 'metric_name'], unique=False)

    op.create_table('vector_stores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=True),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('embedding_model', sa.String(length=64), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('market', sa.String(length=32), nullable=True),
    sa.Column('segment', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_type', 'source_id', 'chunk_index', name='uq_source_chunk')
    )
    with op.batch_alter_table('vector_stores', schema=None) as batch_op:
        batch_op.create_index('idx_vector_project', ['project_id'], unique=False)
        batch_op.create_index('idx_vector_source', ['source_type', 'source_id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('retrieved_chunks', sa.JSON(), nullable=True),
    sa.Column('retrieval_scores', sa.JSON(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('detected_language', sa.String(length=10), nullable=True),
    sa.Column('code_mixed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index('idx_chat_message_session', ['session_id', 'created_at'], unique=False)

    op.create_table('collaboration_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['collaboration_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collaboration_events', schema=None) as batch_op:
        batch_op.create_index('idx_collab_event', ['session_id', 'created_at'], unique=False)
        batch_op.create_index('idx_event_type', ['event_type', 'created_at'], unique=False)

    op.create_table('content_analysis_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('report_type', sa.String(length=32), nullable=True),
    sa.Column('grid_id', sa.String(length=36), nullable=True),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('methodology', sa.Text(), nullable=True),
    sa.Column('key_findings', sa.JSON(), nullable=True),
    sa.Column('themes_analysis', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('market_comparison', sa.JSON(), nullable=True),
    sa.Column('regional_patterns', sa.JSON(), nullable=True),
    sa.Column('statistics', sa.JSON(), nullable=True),
    sa.Column('charts', sa.JSON(), nullable=True),
    sa.Column('evidence_ids', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('generation_params', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('export_formats', sa.JSON(), nullable=True),
    sa.Column('last_exported', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['grid_id'], ['analysis_grids.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grid_cells',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('grid_id', sa.String(length=36), nullable=False),
    sa.Column('row_id', sa.String(length=128), nullable=True),
    sa.Column('column_id', sa.String(length=128), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('evidence_ids', sa.JSON(), nullable=True),
    sa.Column('comparison_dimension', sa.String(length=128), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_patterns', sa.JSON(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['grid_id'], ['analysis_grids.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grid_cells', schema=None) as batch_op:
        batch_op.create_index('idx_grid_cell_position', ['grid_id', 'row_id', 'column_id'], unique=False)

    op.create_table('recording_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('meeting_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('media_id', sa.String(length=32), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media_assets.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('purpose', sa.String(length=64), nullable=True),
    sa.Column('transition_style', sa.String(length=32), nullable=True),
    sa.Column('transition_duration', sa.Float(), nullable=True),
    sa.Column('intro_text', sa.Text(), nullable=True),
    sa.Column('outro_text', sa.Text(), nullable=True),
    sa.Column('watermark', sa.Boolean(), nullable=True),
    sa.Column('resolution', sa.String(length=32), nullable=True),
    sa.Column('aspect_ratio', sa.String(length=32), nullable=True),
    sa.Column('format', sa.String(length=32), nullable=True),
    sa.Column('reel_media_id', sa.String(length=36), nullable=True),
    sa.Column('total_duration', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('share_token', sa.String(length=64), nullable=True),
    sa.Column('share_expires', sa.DateTime(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['reel_media_id'], ['media_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reels', schema=None) as batch_op:
        batch_op.create_index('idx_reel_created', ['created_at'], unique=False)
        batch_op.create_index('idx_reel_project', ['project_id'], unique=False)
        batch_op.create_index('idx_reel_share_token', ['share_token'], unique=False)
        batch_op.create_index('idx_reel_status', ['status'], unique=False)

    op.create_table('clips',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('transcript_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('segment_ids', sa.JSON(), nullable=True),
    sa.Column('source_media_id', sa.String(length=36), nullable=True),
    sa.Column('clip_media_id', sa.String(length=36), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('theme_ids', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clip_media_id'], ['media_assets.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_media_id'], ['media_assets.id'], ),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clips', schema=None) as batch_op:
        batch_op.create_index('idx_clip_created', ['created_at'], unique=False)
        batch_op.create_index('idx_clip_project', ['project_id'], unique=False)
        batch_op.create_index('idx_clip_status', ['status'], unique=False)
        batch_op.create_index('idx_clip_transcript', ['transcript_id'], unique=False)

    op.create_table('reel_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('reel_id', sa.String(length=36), nullable=False),
    sa.Column('clip_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title_overlay', sa.Text(), nullable=True),
    sa.Column('subtitle_overlay', sa.Text(), nullable=True),
    sa.Column('trim_start', sa.Float(), nullable=True),
    sa.Column('trim_end', sa.Float(), nullable=True),
    sa.Column('playback_speed', sa.Float(), nullable=True),
    sa.Column('transition_in', sa.String(length=32), nullable=True),
    sa.Column('transition_out', sa.String(length=32), nullable=True),
    sa.Column('annotations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ),
    sa.ForeignKeyConstraint(['reel_id'], ['reels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reel_id', 'position', name='uq_reel_item_position')
    )
    with op.batch_alter_table('reel_items', schema=None) as batch_op:
        batch_op.create_index('idx_reel_item_clip', ['clip_id'], unique=False)
        batch_op.create_index('idx_reel_item_reel', ['reel_id'], unique=False)

    # import_jobs predates the integrations table, so its integration_id FK was
    # never created. Add it now. On SQLite this recreates the table; supply a
    # naming_convention so the existing (unnamed, since SQLite doesn't persist FK
    # names) constraints can be reflected during the batch recreate.
    with op.batch_alter_table('import_jobs', schema=None,
                              naming_convention=_NAMING) as batch_op:
        batch_op.create_foreign_key('fk_import_jobs_integration', 'integrations',
                                    ['integration_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_jobs', schema=None,
                              naming_convention=_NAMING) as batch_op:
        batch_op.drop_constraint('fk_import_jobs_integration', type_='foreignkey')

    with op.batch_alter_table('reel_items', schema=None) as batch_op:
        batch_op.drop_index('idx_reel_item_reel')
        batch_op.drop_index('idx_reel_item_clip')

    op.drop_table('reel_items')
    with op.batch_alter_table('clips', schema=None) as batch_op:
        batch_op.drop_index('idx_clip_transcript')
        batch_op.drop_index('idx_clip_status')
        batch_op.drop_index('idx_clip_project')
        batch_op.drop_index('idx_clip_created')

    op.drop_table('clips')
    with op.batch_alter_table('reels', schema=None) as batch_op:
        batch_op.drop_index('idx_reel_status')
        batch_op.drop_index('idx_reel_share_token')
        batch_op.drop_index('idx_reel_project')
        batch_op.drop_index('idx_reel_created')

    op.drop_table('reels')
    op.drop_table('recording_sessions')
    with op.batch_alter_table('grid_cells', schema=None) as batch_op:
        batch_op.drop_index('idx_grid_cell_position')

    op.drop_table('grid_cells')
    op.drop_table('content_analysis_reports')
    with op.batch_alter_table('collaboration_events', schema=None) as batch_op:
        batch_op.drop_index('idx_event_type')
        batch_op.drop_index('idx_collab_event')

    op.drop_table('collaboration_events')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index('idx_chat_message_session')

    op.drop_table('chat_messages')
    with op.batch_alter_table('vector_stores', schema=None) as batch_op:
        batch_op.drop_index('idx_vector_source')
        batch_op.drop_index('idx_vector_project')

    op.drop_table('vector_stores')
    with op.batch_alter_table('system_metrics', schema=None) as batch_op:
        batch_op.drop_index('ix_metrics_type_name')
        batch_op.drop_index('ix_metrics_period')
        batch_op.drop_index('ix_metrics_org')

    op.drop_table('system_metrics')
    with op.batch_alter_table('semantic_search_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_search_log_user')
        batch_op.drop_index('idx_search_log_project')
        batch_op.drop_index('idx_search_log_created')

    op.drop_table('semantic_search_logs')
    with op.batch_alter_table('project_activities', schema=None) as batch_op:
        batch_op.drop_index('idx_project_activity')
        batch_op.drop_index('idx_activity_user')

    op.drop_table('project_activities')
    op.drop_table('markets')
    with op.batch_alter_table('knowledge_bases', schema=None) as batch_op:
        batch_op.drop_index('idx_knowledge_base_project')

    op.drop_table('knowledge_bases')
    with op.batch_alter_table('insights', schema=None) as batch_op:
        batch_op.drop_index('idx_insight_priority')

    op.drop_table('insights')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index('idx_evidence_themes')
        batch_op.drop_index('idx_evidence_project')

    op.drop_table('evidence')
    with op.batch_alter_table('custom_field_values', schema=None) as batch_op:
        batch_op.drop_index('ix_custom_value_field_entity')

    op.drop_table('custom_field_values')
    op.drop_table('community_threads')
    with op.batch_alter_table('collaboration_sessions', schema=None) as batch_op:
        batch_op.drop_index('idx_collab_user')
        batch_op.drop_index('idx_collab_session')

    op.drop_table('collaboration_sessions')
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index('idx_chat_session_user')
        batch_op.drop_index('idx_chat_session_project')

    op.drop_table('chat_sessions')
    with op.batch_alter_table('analysis_themes', schema=None) as batch_op:
        batch_op.drop_index('idx_theme_project')
        batch_op.drop_index('idx_theme_hierarchy')

    op.drop_table('analysis_themes')
    op.drop_table('analysis_grids')
    with op.batch_alter_table('share_links', schema=None) as batch_op:
        batch_op.drop_index('idx_share_link_token')
        batch_op.drop_index('idx_share_link_target')
        batch_op.drop_index('idx_share_link_expires')

    op.drop_table('share_links')
    with op.batch_alter_table('saved_prompts', schema=None) as batch_op:
        batch_op.drop_index('idx_saved_prompt_org')
        batch_op.drop_index('idx_saved_prompt_category')

    op.drop_table('saved_prompts')
    with op.batch_alter_table('media_processing_jobs', schema=None) as batch_op:
        batch_op.drop_index('idx_media_job_target')
        batch_op.drop_index('idx_media_job_status')
        batch_op.drop_index('idx_media_job_created')

    op.drop_table('media_processing_jobs')
    with op.batch_alter_table('integration_configs', schema=None) as batch_op:
        batch_op.drop_index('ix_integration_type')
        batch_op.drop_index('ix_integration_org')

    op.drop_table('integration_configs')
    with op.batch_alter_table('data_import_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_import_status')
        batch_op.drop_index('ix_import_org_user')
        batch_op.drop_index('ix_import_created')

    op.drop_table('data_import_jobs')
    with op.batch_alter_table('data_export_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_export_status')
        batch_op.drop_index('ix_export_org_user')
        batch_op.drop_index('ix_export_created')

    op.drop_table('data_export_jobs')
    with op.batch_alter_table('custom_fields', schema=None) as batch_op:
        batch_op.drop_index('ix_custom_field_org_entity')

    op.drop_table('custom_fields')
    with op.batch_alter_table('clip_templates', schema=None) as batch_op:
        batch_op.drop_index('idx_clip_template_org')
        batch_op.drop_index('idx_clip_template_category')

    op.drop_table('clip_templates')
    with op.batch_alter_table('chat_templates', schema=None) as batch_op:
        batch_op.drop_index('idx_chat_template_use_case')
        batch_op.drop_index('idx_chat_template_org')

    op.drop_table('chat_templates')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_org_user')
        batch_op.drop_index('ix_audit_ip')
        batch_op.drop_index('ix_audit_entity')
        batch_op.drop_index('ix_audit_created')
        batch_op.drop_index('ix_audit_action')

    op.drop_table('audit_logs')
    with op.batch_alter_table('white_label_configs', schema=None) as batch_op:
        batch_op.drop_index('ix_white_label_org_id')
        batch_op.drop_index('ix_white_label_custom_domain')

    op.drop_table('white_label_configs')
    with op.batch_alter_table('usage_quotas', schema=None) as batch_op:
        batch_op.drop_index('ix_quota_org')

    op.drop_table('usage_quotas')
    op.drop_table('integrations')
    # ### end Alembic commands ###
