"""Add Phase 5 enterprise tables and collaboration models

Revision ID: a4ed82f6ee87
Revises: manual_001
Create Date: 2026-06-24 16:40:10.994046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'a4ed82f6ee87'
down_revision: Union[str, Sequence[str], None] = 'manual_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _has_table(name: str) -> bool:
    return sa.inspect(op.get_bind()).has_table(name)


def upgrade() -> None:
    """Upgrade schema — create the Phase 5 enterprise / collaboration tables.

    NOTE: this migration was originally autogenerated INVERTED (its upgrade
    dropped these tables and its downgrade created them) which made the chain
    unrunnable from an empty DB. It has been corrected: upgrade now creates the
    tables (guarded so it is also safe on a legacy DB that already has them);
    downgrade drops them. The stray idx_* index churn on core tables (which were
    never created by an earlier migration) was removed.
    """
    # ### corrected: create-before-use, FK-dependency order, idempotent ###
    if not _has_table('open_end_questions'):
        op.create_table('open_end_questions',
        sa.Column('id', sa.VARCHAR(length=36), nullable=False),
        sa.Column('org_id', sa.VARCHAR(length=36), nullable=False),
        sa.Column('project_id', sa.VARCHAR(length=36), nullable=False),
        sa.Column('question_code', sa.VARCHAR(length=64), nullable=False),
        sa.Column('question_text', sa.TEXT(), nullable=False),
        sa.Column('question_type', sa.VARCHAR(length=32), nullable=True),
        sa.Column('wave', sa.INTEGER(), nullable=True),
        sa.Column('survey_name', sa.VARCHAR(length=256), nullable=True),
        sa.Column('code_frame', sa.JSON(), nullable=True),
        sa.Column('allow_multiple', sa.BOOLEAN(), nullable=True),
        sa.Column('other_specify', sa.BOOLEAN(), nullable=True),
        sa.Column('total_responses', sa.INTEGER(), nullable=True),
        sa.Column('coded_responses', sa.INTEGER(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.VARCHAR(length=36), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
        sa.PrimaryKeyConstraint('id')
        )

    if not _has_table('concept_tests'):
        op.create_table('concept_tests',
        sa.Column('id', sa.VARCHAR(length=36), nullable=False),
        sa.Column('org_id', sa.VARCHAR(length=36), nullable=False),
        sa.Column('project_id', sa.VARCHAR(length=36), nullable=False),
        sa.Column('name', sa.VARCHAR(length=256), nullable=False),
        sa.Column('description', sa.TEXT(), nullable=True),
        sa.Column('test_type', sa.VARCHAR(length=64), nullable=True),
        sa.Column('concepts', sa.JSON(), nullable=True),
        sa.Column('metrics', sa.JSON(), nullable=True),
        sa.Column('target_audience', sa.TEXT(), nullable=True),
        sa.Column('sample_size', sa.INTEGER(), nullable=True),
        sa.Column('markets', sa.JSON(), nullable=True),
        sa.Column('status', sa.VARCHAR(length=32), nullable=True),
        sa.Column('start_date', sa.DateTime(), nullable=True),
        sa.Column('end_date', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.VARCHAR(length=36), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
        sa.PrimaryKeyConstraint('id')
        )

    if not _has_table('code_frames'):
        op.create_table('code_frames',
        sa.Column('id', sa.VARCHAR(length=36), nullable=False),
        sa.Column('question_id', sa.VARCHAR(length=36), nullable=False),
        sa.Column('code', sa.VARCHAR(length=64), nullable=False),
        sa.Column('label', sa.VARCHAR(length=256), nullable=False),
        sa.Column('description', sa.TEXT(), nullable=True),
        sa.Column('parent_code', sa.VARCHAR(length=64), nullable=True),
        sa.Column('level', sa.INTEGER(), nullable=True),
        sa.Column('sort_order', sa.INTEGER(), nullable=True),
        sa.Column('usage_count', sa.INTEGER(), nullable=True),
        sa.Column('is_exclusive', sa.BOOLEAN(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.VARCHAR(length=36), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['question_id'], ['open_end_questions.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('question_id', 'code', name=op.f('uq_code_frame'))
        )
        op.create_index(op.f('idx_code_frame_question'), 'code_frames', ['question_id'], unique=False)

    if not _has_table('open_end_responses'):
        op.create_table('open_end_responses',
        sa.Column('id', sa.VARCHAR(length=36), nullable=False),
        sa.Column('question_id', sa.VARCHAR(length=36), nullable=False),
        sa.Column('respondent_id', sa.VARCHAR(length=128), nullable=True),
        sa.Column('response_text', sa.TEXT(), nullable=False),
        sa.Column('language', sa.VARCHAR(length=10), nullable=True),
        sa.Column('codes', sa.JSON(), nullable=True),
        sa.Column('coded_by', sa.VARCHAR(length=36), nullable=True),
        sa.Column('coded_at', sa.DateTime(), nullable=True),
        sa.Column('reviewed_by', sa.VARCHAR(length=36), nullable=True),
        sa.Column('reviewed_at', sa.DateTime(), nullable=True),
        sa.Column('review_status', sa.VARCHAR(length=32), nullable=True),
        sa.Column('review_notes', sa.TEXT(), nullable=True),
        sa.Column('ai_suggested_codes', sa.JSON(), nullable=True),
        sa.Column('ai_confidence', sa.FLOAT(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['coded_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['question_id'], ['open_end_questions.id'], ),
        sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('idx_open_end_response_respondent'), 'open_end_responses', ['respondent_id'], unique=False)
        op.create_index(op.f('idx_open_end_response_question'), 'open_end_responses', ['question_id'], unique=False)

    if not _has_table('concept_evaluations'):
        op.create_table('concept_evaluations',
        sa.Column('id', sa.VARCHAR(length=36), nullable=False),
        sa.Column('test_id', sa.VARCHAR(length=36), nullable=False),
        sa.Column('respondent_id', sa.VARCHAR(length=128), nullable=True),
        sa.Column('concept_id', sa.VARCHAR(length=64), nullable=True),
        sa.Column('ratings', sa.JSON(), nullable=True),
        sa.Column('overall_rating', sa.FLOAT(), nullable=True),
        sa.Column('likes', sa.TEXT(), nullable=True),
        sa.Column('dislikes', sa.TEXT(), nullable=True),
        sa.Column('suggestions', sa.TEXT(), nullable=True),
        sa.Column('purchase_intent', sa.INTEGER(), nullable=True),
        sa.Column('demographic_data', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['test_id'], ['concept_tests.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('idx_concept_eval_test'), 'concept_evaluations', ['test_id'], unique=False)
        op.create_index(op.f('idx_concept_eval_respondent'), 'concept_evaluations', ['respondent_id'], unique=False)

    if not _has_table('activity_logs'):
        op.create_table('activity_logs',
        sa.Column('id', sa.VARCHAR(length=36), nullable=False),
        sa.Column('org_id', sa.VARCHAR(length=36), nullable=False),
        sa.Column('project_id', sa.VARCHAR(length=36), nullable=True),
        sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
        sa.Column('action', sa.VARCHAR(length=64), nullable=False),
        sa.Column('target_type', sa.VARCHAR(length=64), nullable=True),
        sa.Column('target_id', sa.VARCHAR(length=36), nullable=True),
        sa.Column('target_name', sa.VARCHAR(length=256), nullable=True),
        sa.Column('details', sa.JSON(), nullable=True),
        sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True),
        sa.Column('user_agent', sa.VARCHAR(length=512), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('idx_activity_log_user'), 'activity_logs', ['user_id'], unique=False)
        op.create_index(op.f('idx_activity_log_project'), 'activity_logs', ['project_id'], unique=False)
        op.create_index(op.f('idx_activity_log_created'), 'activity_logs', ['created_at'], unique=False)
        op.create_index(op.f('idx_activity_log_action'), 'activity_logs', ['action'], unique=False)

    if not _has_table('organization_stats'):
        op.create_table('organization_stats',
        sa.Column('id', sa.VARCHAR(length=36), nullable=False),
        sa.Column('org_id', sa.VARCHAR(length=36), nullable=False),
        sa.Column('total_users', sa.INTEGER(), nullable=True),
        sa.Column('active_users_today', sa.INTEGER(), nullable=True),
        sa.Column('active_users_week', sa.INTEGER(), nullable=True),
        sa.Column('active_users_month', sa.INTEGER(), nullable=True),
        sa.Column('total_projects', sa.INTEGER(), nullable=True),
        sa.Column('active_projects', sa.INTEGER(), nullable=True),
        sa.Column('completed_projects', sa.INTEGER(), nullable=True),
        sa.Column('total_transcripts', sa.INTEGER(), nullable=True),
        sa.Column('total_analyses', sa.INTEGER(), nullable=True),
        sa.Column('total_evidence', sa.INTEGER(), nullable=True),
        sa.Column('total_ai_calls', sa.INTEGER(), nullable=True),
        sa.Column('total_chat_messages', sa.INTEGER(), nullable=True),
        sa.Column('storage_used_mb', sa.FLOAT(), nullable=True),
        sa.Column('total_questions', sa.INTEGER(), nullable=True),
        sa.Column('total_responses', sa.INTEGER(), nullable=True),
        sa.Column('coding_completion_rate', sa.FLOAT(), nullable=True),
        sa.Column('calculated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('idx_org_stats'), 'organization_stats', ['org_id', 'calculated_at'], unique=False)

    if not _has_table('user_enhancements'):
        op.create_table('user_enhancements',
        sa.Column('id', sa.VARCHAR(length=36), nullable=False),
        sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
        sa.Column('team', sa.VARCHAR(length=32), nullable=True),
        sa.Column('department', sa.VARCHAR(length=128), nullable=True),
        sa.Column('job_title', sa.VARCHAR(length=128), nullable=True),
        sa.Column('avatar_url', sa.VARCHAR(length=512), nullable=True),
        sa.Column('bio', sa.TEXT(), nullable=True),
        sa.Column('timezone', sa.VARCHAR(length=64), nullable=True),
        sa.Column('language_preference', sa.VARCHAR(length=10), nullable=True),
        sa.Column('can_create_projects', sa.BOOLEAN(), nullable=True),
        sa.Column('can_manage_users', sa.BOOLEAN(), nullable=True),
        sa.Column('can_export_data', sa.BOOLEAN(), nullable=True),
        sa.Column('can_delete_content', sa.BOOLEAN(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id')
        )

    if not _has_table('notifications'):
        op.create_table('notifications',
        sa.Column('id', sa.VARCHAR(length=36), nullable=False),
        sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
        sa.Column('type', sa.VARCHAR(length=64), nullable=False),
        sa.Column('title', sa.VARCHAR(length=256), nullable=False),
        sa.Column('message', sa.TEXT(), nullable=True),
        sa.Column('link_type', sa.VARCHAR(length=64), nullable=True),
        sa.Column('link_id', sa.VARCHAR(length=36), nullable=True),
        sa.Column('is_read', sa.BOOLEAN(), nullable=True),
        sa.Column('read_at', sa.DateTime(), nullable=True),
        sa.Column('priority', sa.VARCHAR(length=32), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('expires_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('idx_notification_user'), 'notifications', ['user_id', 'is_read'], unique=False)
        op.create_index(op.f('idx_notification_created'), 'notifications', ['created_at'], unique=False)

    if not _has_table('comments'):
        op.create_table('comments',
        sa.Column('id', sa.VARCHAR(length=36), nullable=False),
        sa.Column('org_id', sa.VARCHAR(length=36), nullable=False),
        sa.Column('target_type', sa.VARCHAR(length=64), nullable=False),
        sa.Column('target_id', sa.VARCHAR(length=36), nullable=False),
        sa.Column('content', sa.TEXT(), nullable=False),
        sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
        sa.Column('parent_id', sa.VARCHAR(length=36), nullable=True),
        sa.Column('mentioned_users', sa.JSON(), nullable=True),
        sa.Column('is_resolved', sa.BOOLEAN(), nullable=True),
        sa.Column('resolved_by', sa.VARCHAR(length=36), nullable=True),
        sa.Column('resolved_at', sa.DateTime(), nullable=True),
        sa.Column('is_edited', sa.BOOLEAN(), nullable=True),
        sa.Column('edited_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
        sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ),
        sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('idx_comment_user'), 'comments', ['user_id'], unique=False)
        op.create_index(op.f('idx_comment_target'), 'comments', ['target_type', 'target_id'], unique=False)
        op.create_index(op.f('idx_comment_parent'), 'comments', ['parent_id'], unique=False)

    if not _has_table('project_members'):
        op.create_table('project_members',
        sa.Column('id', sa.VARCHAR(length=36), nullable=False),
        sa.Column('project_id', sa.VARCHAR(length=36), nullable=False),
        sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
        sa.Column('role', sa.VARCHAR(length=32), nullable=True),
        sa.Column('can_edit_transcripts', sa.BOOLEAN(), nullable=True),
        sa.Column('can_run_analysis', sa.BOOLEAN(), nullable=True),
        sa.Column('can_manage_team', sa.BOOLEAN(), nullable=True),
        sa.Column('can_export', sa.BOOLEAN(), nullable=True),
        sa.Column('can_delete', sa.BOOLEAN(), nullable=True),
        sa.Column('assigned_by', sa.VARCHAR(length=36), nullable=True),
        sa.Column('assigned_at', sa.DateTime(), nullable=True),
        sa.Column('last_accessed', sa.DateTime(), nullable=True),
        sa.Column('access_count', sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('project_id', 'user_id', name=op.f('uq_project_member'))
        )
        op.create_index(op.f('idx_project_member_user'), 'project_members', ['user_id'], unique=False)
        op.create_index(op.f('idx_project_member_project'), 'project_members', ['project_id'], unique=False)
    # ### end corrected ###


def downgrade() -> None:
    """Downgrade schema — drop the Phase 5 tables (reverse dependency order)."""
    for table in ('project_members', 'comments', 'notifications', 'user_enhancements',
                  'organization_stats', 'activity_logs', 'concept_evaluations',
                  'open_end_responses', 'code_frames', 'concept_tests', 'open_end_questions'):
        if _has_table(table):
            op.drop_table(table)


