"""Add Phase 5 enterprise tables and collaboration models

Revision ID: a4ed82f6ee87
Revises: manual_001
Create Date: 2026-06-24 16:40:10.994046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'a4ed82f6ee87'
down_revision: Union[str, Sequence[str], None] = 'manual_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_project_member_project'), table_name='project_members')
    op.drop_index(op.f('idx_project_member_user'), table_name='project_members')
    op.drop_table('project_members')
    op.drop_index(op.f('idx_open_end_questions_project_id'), table_name='open_end_questions')
    op.drop_table('open_end_questions')
    op.drop_index(op.f('idx_comment_parent'), table_name='comments')
    op.drop_index(op.f('idx_comment_target'), table_name='comments')
    op.drop_index(op.f('idx_comment_user'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('idx_notification_created'), table_name='notifications')
    op.drop_index(op.f('idx_notification_user'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('user_enhancements')
    op.drop_index(op.f('idx_open_end_response_question'), table_name='open_end_responses')
    op.drop_index(op.f('idx_open_end_response_respondent'), table_name='open_end_responses')
    op.drop_index(op.f('idx_open_end_responses_question_id'), table_name='open_end_responses')
    op.drop_table('open_end_responses')
    op.drop_table('concept_tests')
    op.drop_index(op.f('idx_org_stats'), table_name='organization_stats')
    op.drop_table('organization_stats')
    op.drop_index(op.f('idx_activity_log_action'), table_name='activity_logs')
    op.drop_index(op.f('idx_activity_log_created'), table_name='activity_logs')
    op.drop_index(op.f('idx_activity_log_project'), table_name='activity_logs')
    op.drop_index(op.f('idx_activity_log_user'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('idx_concept_eval_respondent'), table_name='concept_evaluations')
    op.drop_index(op.f('idx_concept_eval_test'), table_name='concept_evaluations')
    op.drop_table('concept_evaluations')
    op.drop_index(op.f('idx_code_frame_question'), table_name='code_frames')
    op.drop_table('code_frames')
    op.drop_index(op.f('idx_analyses_created_at'), table_name='analyses')
    op.drop_index(op.f('idx_analyses_org_created'), table_name='analyses')
    op.drop_index(op.f('idx_analyses_status'), table_name='analyses')
    op.drop_index(op.f('idx_analyses_transcript_id'), table_name='analyses')
    op.drop_index(op.f('idx_analyses_transcript_id_status'), table_name='analyses')
    op.drop_index(op.f('idx_orgs_plan'), table_name='orgs')
    op.drop_index(op.f('idx_projects_created_at'), table_name='projects')
    op.drop_index(op.f('idx_projects_org_id'), table_name='projects')
    op.drop_index(op.f('idx_projects_org_id_created_at'), table_name='projects')
    op.drop_index(op.f('idx_projects_status'), table_name='projects')
    op.drop_index(op.f('idx_themes_analysis_id'), table_name='themes')
    op.drop_index(op.f('idx_transcript_segments_transcript_id'), table_name='transcript_segments')
    op.drop_index(op.f('idx_transcript_org_project'), table_name='transcripts')
    op.drop_index(op.f('idx_transcripts_created_at'), table_name='transcripts')
    op.drop_index(op.f('idx_transcripts_project_id'), table_name='transcripts')
    op.drop_index(op.f('idx_transcripts_project_id_created_at'), table_name='transcripts')
    op.drop_index(op.f('idx_transcripts_transcription_status'), table_name='transcripts')
    op.drop_index(op.f('idx_usage_org_created'), table_name='usage_records')
    op.drop_index(op.f('idx_usage_records_created_at'), table_name='usage_records')
    op.drop_index(op.f('idx_usage_records_org_id'), table_name='usage_records')
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_org_id'), table_name='users')
    op.drop_index(op.f('idx_verbatims_theme_id'), table_name='verbatims')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_verbatims_theme_id'), 'verbatims', ['theme_id'], unique=False)
    op.create_index(op.f('idx_users_org_id'), 'users', ['org_id'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('idx_usage_records_org_id'), 'usage_records', ['org_id'], unique=False)
    op.create_index(op.f('idx_usage_records_created_at'), 'usage_records', ['created_at'], unique=False)
    op.create_index(op.f('idx_usage_org_created'), 'usage_records', ['org_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_transcripts_transcription_status'), 'transcripts', ['transcription_status'], unique=False)
    op.create_index(op.f('idx_transcripts_project_id_created_at'), 'transcripts', ['project_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_transcripts_project_id'), 'transcripts', ['project_id'], unique=False)
    op.create_index(op.f('idx_transcripts_created_at'), 'transcripts', ['created_at'], unique=False)
    op.create_index(op.f('idx_transcript_org_project'), 'transcripts', ['org_id', 'project_id'], unique=False)
    op.create_index(op.f('idx_transcript_segments_transcript_id'), 'transcript_segments', ['transcript_id'], unique=False)
    op.create_index(op.f('idx_themes_analysis_id'), 'themes', ['analysis_id'], unique=False)
    op.create_index(op.f('idx_projects_status'), 'projects', ['status'], unique=False)
    op.create_index(op.f('idx_projects_org_id_created_at'), 'projects', ['org_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_projects_org_id'), 'projects', ['org_id'], unique=False)
    op.create_index(op.f('idx_projects_created_at'), 'projects', ['created_at'], unique=False)
    op.create_index(op.f('idx_orgs_plan'), 'orgs', ['plan'], unique=False)
    op.create_index(op.f('idx_analyses_transcript_id_status'), 'analyses', ['transcript_id', 'status'], unique=False)
    op.create_index(op.f('idx_analyses_transcript_id'), 'analyses', ['transcript_id'], unique=False)
    op.create_index(op.f('idx_analyses_status'), 'analyses', ['status'], unique=False)
    op.create_index(op.f('idx_analyses_org_created'), 'analyses', ['org_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_analyses_created_at'), 'analyses', ['created_at'], unique=False)
    op.create_table('code_frames',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('question_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('code', sa.VARCHAR(length=64), nullable=False),
    sa.Column('label', sa.VARCHAR(length=256), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('parent_code', sa.VARCHAR(length=64), nullable=True),
    sa.Column('level', sa.INTEGER(), nullable=True),
    sa.Column('sort_order', sa.INTEGER(), nullable=True),
    sa.Column('usage_count', sa.INTEGER(), nullable=True),
    sa.Column('is_exclusive', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['open_end_questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'code', name=op.f('uq_code_frame'))
    )
    op.create_index(op.f('idx_code_frame_question'), 'code_frames', ['question_id'], unique=False)
    op.create_table('concept_evaluations',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('test_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('respondent_id', sa.VARCHAR(length=128), nullable=True),
    sa.Column('concept_id', sa.VARCHAR(length=64), nullable=True),
    sa.Column('ratings', sqlite.JSON(), nullable=True),
    sa.Column('overall_rating', sa.FLOAT(), nullable=True),
    sa.Column('likes', sa.TEXT(), nullable=True),
    sa.Column('dislikes', sa.TEXT(), nullable=True),
    sa.Column('suggestions', sa.TEXT(), nullable=True),
    sa.Column('purchase_intent', sa.INTEGER(), nullable=True),
    sa.Column('demographic_data', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['concept_tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_concept_eval_test'), 'concept_evaluations', ['test_id'], unique=False)
    op.create_index(op.f('idx_concept_eval_respondent'), 'concept_evaluations', ['respondent_id'], unique=False)
    op.create_table('activity_logs',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('org_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('project_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('action', sa.VARCHAR(length=64), nullable=False),
    sa.Column('target_type', sa.VARCHAR(length=64), nullable=True),
    sa.Column('target_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('target_name', sa.VARCHAR(length=256), nullable=True),
    sa.Column('details', sqlite.JSON(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=512), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_activity_log_user'), 'activity_logs', ['user_id'], unique=False)
    op.create_index(op.f('idx_activity_log_project'), 'activity_logs', ['project_id'], unique=False)
    op.create_index(op.f('idx_activity_log_created'), 'activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('idx_activity_log_action'), 'activity_logs', ['action'], unique=False)
    op.create_table('organization_stats',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('org_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('total_users', sa.INTEGER(), nullable=True),
    sa.Column('active_users_today', sa.INTEGER(), nullable=True),
    sa.Column('active_users_week', sa.INTEGER(), nullable=True),
    sa.Column('active_users_month', sa.INTEGER(), nullable=True),
    sa.Column('total_projects', sa.INTEGER(), nullable=True),
    sa.Column('active_projects', sa.INTEGER(), nullable=True),
    sa.Column('completed_projects', sa.INTEGER(), nullable=True),
    sa.Column('total_transcripts', sa.INTEGER(), nullable=True),
    sa.Column('total_analyses', sa.INTEGER(), nullable=True),
    sa.Column('total_evidence', sa.INTEGER(), nullable=True),
    sa.Column('total_ai_calls', sa.INTEGER(), nullable=True),
    sa.Column('total_chat_messages', sa.INTEGER(), nullable=True),
    sa.Column('storage_used_mb', sa.FLOAT(), nullable=True),
    sa.Column('total_questions', sa.INTEGER(), nullable=True),
    sa.Column('total_responses', sa.INTEGER(), nullable=True),
    sa.Column('coding_completion_rate', sa.FLOAT(), nullable=True),
    sa.Column('calculated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_org_stats'), 'organization_stats', ['org_id', 'calculated_at'], unique=False)
    op.create_table('concept_tests',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('org_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('project_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('test_type', sa.VARCHAR(length=64), nullable=True),
    sa.Column('concepts', sqlite.JSON(), nullable=True),
    sa.Column('metrics', sqlite.JSON(), nullable=True),
    sa.Column('target_audience', sa.TEXT(), nullable=True),
    sa.Column('sample_size', sa.INTEGER(), nullable=True),
    sa.Column('markets', sqlite.JSON(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=32), nullable=True),
    sa.Column('start_date', sa.DATETIME(), nullable=True),
    sa.Column('end_date', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('open_end_responses',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('question_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('respondent_id', sa.VARCHAR(length=128), nullable=True),
    sa.Column('response_text', sa.TEXT(), nullable=False),
    sa.Column('language', sa.VARCHAR(length=10), nullable=True),
    sa.Column('codes', sqlite.JSON(), nullable=True),
    sa.Column('coded_by', sa.VARCHAR(length=36), nullable=True),
    sa.Column('coded_at', sa.DATETIME(), nullable=True),
    sa.Column('reviewed_by', sa.VARCHAR(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DATETIME(), nullable=True),
    sa.Column('review_status', sa.VARCHAR(length=32), nullable=True),
    sa.Column('review_notes', sa.TEXT(), nullable=True),
    sa.Column('ai_suggested_codes', sqlite.JSON(), nullable=True),
    sa.Column('ai_confidence', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['coded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['open_end_questions.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_open_end_responses_question_id'), 'open_end_responses', ['question_id'], unique=False)
    op.create_index(op.f('idx_open_end_response_respondent'), 'open_end_responses', ['respondent_id'], unique=False)
    op.create_index(op.f('idx_open_end_response_question'), 'open_end_responses', ['question_id'], unique=False)
    op.create_table('user_enhancements',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('team', sa.VARCHAR(length=32), nullable=True),
    sa.Column('department', sa.VARCHAR(length=128), nullable=True),
    sa.Column('job_title', sa.VARCHAR(length=128), nullable=True),
    sa.Column('avatar_url', sa.VARCHAR(length=512), nullable=True),
    sa.Column('bio', sa.TEXT(), nullable=True),
    sa.Column('timezone', sa.VARCHAR(length=64), nullable=True),
    sa.Column('language_preference', sa.VARCHAR(length=10), nullable=True),
    sa.Column('can_create_projects', sa.BOOLEAN(), nullable=True),
    sa.Column('can_manage_users', sa.BOOLEAN(), nullable=True),
    sa.Column('can_export_data', sa.BOOLEAN(), nullable=True),
    sa.Column('can_delete_content', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('type', sa.VARCHAR(length=64), nullable=False),
    sa.Column('title', sa.VARCHAR(length=256), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=True),
    sa.Column('link_type', sa.VARCHAR(length=64), nullable=True),
    sa.Column('link_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), nullable=True),
    sa.Column('read_at', sa.DATETIME(), nullable=True),
    sa.Column('priority', sa.VARCHAR(length=32), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_notification_user'), 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index(op.f('idx_notification_created'), 'notifications', ['created_at'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('org_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('target_type', sa.VARCHAR(length=64), nullable=False),
    sa.Column('target_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('parent_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('mentioned_users', sqlite.JSON(), nullable=True),
    sa.Column('is_resolved', sa.BOOLEAN(), nullable=True),
    sa.Column('resolved_by', sa.VARCHAR(length=36), nullable=True),
    sa.Column('resolved_at', sa.DATETIME(), nullable=True),
    sa.Column('is_edited', sa.BOOLEAN(), nullable=True),
    sa.Column('edited_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_comment_user'), 'comments', ['user_id'], unique=False)
    op.create_index(op.f('idx_comment_target'), 'comments', ['target_type', 'target_id'], unique=False)
    op.create_index(op.f('idx_comment_parent'), 'comments', ['parent_id'], unique=False)
    op.create_table('open_end_questions',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('org_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('project_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('question_code', sa.VARCHAR(length=64), nullable=False),
    sa.Column('question_text', sa.TEXT(), nullable=False),
    sa.Column('question_type', sa.VARCHAR(length=32), nullable=True),
    sa.Column('wave', sa.INTEGER(), nullable=True),
    sa.Column('survey_name', sa.VARCHAR(length=256), nullable=True),
    sa.Column('code_frame', sqlite.JSON(), nullable=True),
    sa.Column('allow_multiple', sa.BOOLEAN(), nullable=True),
    sa.Column('other_specify', sa.BOOLEAN(), nullable=True),
    sa.Column('total_responses', sa.INTEGER(), nullable=True),
    sa.Column('coded_responses', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_open_end_questions_project_id'), 'open_end_questions', ['project_id'], unique=False)
    op.create_table('project_members',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('project_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('role', sa.VARCHAR(length=32), nullable=True),
    sa.Column('can_edit_transcripts', sa.BOOLEAN(), nullable=True),
    sa.Column('can_run_analysis', sa.BOOLEAN(), nullable=True),
    sa.Column('can_manage_team', sa.BOOLEAN(), nullable=True),
    sa.Column('can_export', sa.BOOLEAN(), nullable=True),
    sa.Column('can_delete', sa.BOOLEAN(), nullable=True),
    sa.Column('assigned_by', sa.VARCHAR(length=36), nullable=True),
    sa.Column('assigned_at', sa.DATETIME(), nullable=True),
    sa.Column('last_accessed', sa.DATETIME(), nullable=True),
    sa.Column('access_count', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name=op.f('uq_project_member'))
    )
    op.create_index(op.f('idx_project_member_user'), 'project_members', ['user_id'], unique=False)
    op.create_index(op.f('idx_project_member_project'), 'project_members', ['project_id'], unique=False)
    # ### end Alembic commands ###
