"""Add Phase 7 visualization tables

Revision ID: c3f8a9d5e2b7
Revises: b7e9f3d2a1c8
Create Date: 2024-12-24 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c3f8a9d5e2b7'
down_revision = 'b7e9f3d2a1c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Neutralised (dialect-safe no-op).

    The original autogenerated body created tables for a superseded media /
    visualization design plus Postgres-only ``CREATE TYPE ... AS ENUM`` DDL that
    is invalid on SQLite, which broke ``alembic upgrade head`` from an empty DB.
    Those tables are no longer part of the models. The current schema is built by
    the schema-reconciliation migration at the head of the chain, so this
    revision is intentionally a no-op (kept to preserve the revision graph).
    """
    pass


def downgrade() -> None:
    pass
