"""Add Phase 4 Open Ends, Concept Testing and Team Collaboration models

Revision ID: f6160569f89c
Revises: bd383c996227
Create Date: 2026-06-22 15:12:38.250987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6160569f89c'
down_revision: Union[str, Sequence[str], None] = 'bd383c996227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
